# MAIA - Ejercicios clase 4

## Ejercicio 1

$$
x_{n+1} = Ax_n + B\xi_n\\
y_n = Cx_n + \eta_n\\
$$


$$
S_r = gen(y_0,y_1,...,y_n)
$$


$$
\hat{x_{n/r}} = P_{S_r}(x_n) = \sum_i^r \frac{<x_n,y_i>}{<y_i,y_i>}y_i
$$


1. 

$$
g_j = y_j - C\hat{x}_{j/j-1}
$$

Todo vector $v \in S_r$ puede ser expresado como una combinación lineal de $y_0,y_1,...,y_n$ y también puede ser expresado como una combinación lineal de $g_0,g_1,...,g_r$. Esto quiere decir que existen $\alpha_0,\alpha_1,...\alpha_r y \beta_0,\beta_1,...,\beta_r \in \Bbb{R}$ tales que:

$$
v = \sum_i^n \alpha_i y_i = \sum_i^n \alpha_i Cx_i + \alpha \eta_i
$$

y también:

$$
v = \sum_i^r \beta g_i 
  = \sum_i^r \beta_i y_i - \beta_i C\hat{x}_{i/i-1} 
  = \sum_i^r \beta_i Cx_i + \beta_i\eta_i - \beta_i C\hat{x}_{i/i-1}
  = \sum_i^r \beta_i Cx_i + \beta_i\eta_i - \beta_i C\sum_j^r \frac{<x_i,y_j>}{<y_j,y_j>}y_j
$$

2. 


3. 


4. 


5. 


6. 


7. 


8. 


9. 


10. 

11. 

## Ejercicio 2

Dados los puntos $(x_0, y_0),(x_1,y_1),...,(x_n, y_n)$. 
¿Cómo calcuları́a la recta $\hat{y} = a_1 x + a_0$ que mejor aproxima (en términos de la distancia 2) los datos obtenidos?, es decir los valores de $a_0$ y $a_1$.

$$
X =
\begin{bmatrix}
x_0 \\
x_1 \\
... \\
x_n \\
\end{bmatrix}
,
Y =
\begin{bmatrix}
y_0 \\
y_1 \\
... \\
y_n \\
\end{bmatrix}
$$

In [ ]:
(x-)

Se buscan los valores de $a_1$ y $a_0$ 

$$
J(a0,a1) = \left\lVert \hat{y} - Y \right\rVert_2
$$

$$
a_1X + a_0 = y
$$

Repita el ejercicio suponiendo que quiere hallar el polinomio que mejor aproxima:

$$
y = a_2 x^2 + a_1x + a_0
$$

## Ejercicio 3

In [1]:
import numpy as np

In [12]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])

q, r = np.linalg.qr(A)
q, r, np.dot(q, r)

(array([[-0.16903085,  0.89708523],
        [-0.50709255,  0.27602622],
        [-0.84515425, -0.34503278]]),
 array([[-5.91607978, -7.43735744],
        [ 0.        ,  0.82807867]]),
 array([[1., 2.],
        [3., 4.],
        [5., 6.]]))

In [10]:
A = np.array([
    [1,2],
    [1,2]
])

q, r = np.linalg.qr(A)
q, r, np.dot(q, r)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([[-1.41421356e+00, -2.82842712e+00],
        [ 0.00000000e+00, -9.48853707e-17]]),
 array([[1., 2.],
        [1., 2.]]))