# Clase 1. Ejercicios

(Explicación en 02:40:14)

1. Dado un corpus de documentos representados por una lista de textos, devolver una matriz con la representación one-hot-encoding.


In [149]:
import numpy as np
from itertools import chain

In [195]:
corpus = [ 
    "hola como estas", 
    "hola como estas y como llego al subte",
    "como llego al subte",
    "esta palabra se repite mucho mucho mucho"
]

def get_vocab_from_corpus(corpus):
    return np.unique(list(chain.from_iterable(map(str.split, corpus))))

In [196]:
vocab = get_vocab_from_corpus(corpus)
vocab

array(['al', 'como', 'esta', 'estas', 'hola', 'llego', 'mucho', 'palabra',
       'repite', 'se', 'subte', 'y'], dtype='<U7')

Ejemplo. Ver un documento.

In [152]:
doc1 = corpus[0]
doc1

'hola como estas'

Expresar un documento cómo una lista de índices de un vocabulario.

In [142]:
def get_vocab_indexes(doc,vocab):
    splitted_doc = doc.split()
    return np.array([np.where(vocab==x) for x in splitted_doc]).flatten()

In [143]:
get_vocab_indexes(doc1,vocab)

array([3, 1, 2])

One Hot Encode.

In [171]:
def one_hot_encode_doc(doc,vocab):
    doc_ohe = np.zeros(vocab.size)
    doc_ohe[get_vocab_indexes(doc,vocab)] = 1
    return doc_ohe

In [182]:
def one_hot_encode_corpus(corpus,vocab):
    corpus_ohe = np.zeros(shape=(len(corpus),vocab.size))
    for idx, doc in enumerate(corpus):
        corpus_ohe[idx] = one_hot_encode_doc(doc,vocab)
    return corpus_ohe

corpus_ohe = one_hot_encode_corpus(corpus,vocab)
corpus_ohe

array([[0., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 1., 1., 0.]])

2. Dado un corpus de documentos representados por una lista de textos, devolver una matriz con la representación vectores de frecuencia.

In [203]:
def freq_encode_doc(doc,vocab):
    doc_freq = np.zeros(vocab.size)
    unique_idx,freq = np.unique(get_vocab_indexes(doc,vocab), return_counts=True)
    doc_freq[unique_idx] = freq
    return doc_freq

In [206]:
doc2 = corpus[3]
doc2
print(doc2)
print(freq_encode_doc(doc2,vocab))

esta palabra se repite mucho mucho mucho
[0. 0. 1. 0. 0. 0. 3. 1. 1. 1. 0. 0.]


In [207]:
def freq_encode_corpus(corpus,vocab):
    corpus_freq = np.zeros(shape=(len(corpus),vocab.size))
    for idx, doc in enumerate(corpus):
        corpus_freq[idx] = freq_encode_doc(doc,vocab)
    return corpus_freq

corpus_freq = freq_encode_corpus(corpus,vocab)
corpus_freq

array([[0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 2., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 3., 1., 1., 1., 0., 0.]])

3. Dado un corpus de documentos representados por una lista de textos, devolver una matriz con la representación TFIDF.

In [ ]:
#TODO

4. Escribir una función que reciba la matriz representando el corpus y el índice de un documento y devuelva los documentos ordenados por similitud coseno.

In [209]:
doc1 = corpus_freq[0]
doc2 = corpus_freq[1]

def cosine_similarity(doc1,doc2):
    return np.dot(doc1,doc2)/( np.linalg.norm(doc1) * np.linalg.norm(doc2) )

cosine_similarity(doc1,doc2)

0.7302967433402214

In [ ]:
def sort_docs_by_cosine_similarity(corpus,doc_index):
    #TODO
    return result

5. Implementar (3) con matrices sparse de la librería SciPy

In [210]:
#TODO