# Clase 01 - NN mínima con XOR

$$
z^{(i)} = w^{(i)T}\hat{x}+b^{(i)}\\
a^{(i)} = g^{(i)}(z^{(i)})\\
$$

In [1]:
import numpy as np

In [108]:
dataset = np.array([
    [0,0,0],
    [0,1,1],
    [1,0,1],
    [1,1,0]
])
n = dataset.shape[0]
dataset

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [111]:
X_train = dataset[:,:2]
X_train.shape

(4, 2)

In [113]:
y_train = dataset[:,2].reshape(-1,1)
y_train.shape

(4, 1)

In [114]:
X_train, y_train

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [121]:


forward_pass(X_train[0],w11,w12,b1,w21,w22,b2,w1,w2,b)

-0.049807600445600286

In [37]:
def g(x):
    return x

In [126]:
def forward_pass(x,w11,w12,b1,w21,w22,b2,w1,w2,b):
    z1 = x[0]*w11 + x[1]*w12 + b1
    z2 = x[0]*w21 + x[1]*w22 + b2
    a1 = g(z1)
    a2 = g(z2)
    y=a1*w1 + a2*w2 + b
    return y,a1,a2

In [57]:
def cost(y_hat,y):
    return (y-yhat)**2

array([[0],
       [0]])

In [106]:
X_train[0]

array([0])

In [1]:
def sgd(X_train, y_train,n_epochs=10,lr=0.01):
    # Input layer
    n = X_train.shape[0] # num_samples
    m = X_train.shape[1] # num_features
    
    # Intialize params with random (non vectorized)
    w11=np.random.randn()
    w12=np.random.randn()
    b1=np.random.randn()
    w21=np.random.randn()
    w22=np.random.randn()
    b2=np.random.randn()
    w1=np.random.randn()
    w2=np.random.randn()
    b=np.random.randn()

    for i in range(n_epochs):
        average_error = 0
        for j in range(n):
            # F -> z1,z2,z1,z2,y
            x = X_train[j]
            y_hat,a1,a2 = forward_pass(x,w11,w12,b1,w21,w22,b2,w1,w2,b)
            error = np.sum((y_train[j]-y_hat)**2)
            average_error += error
            
            # B -> output -> w1,w2
            #   -> hidden
            # Compute gradients
            dw1 = -2*error*a1
            dw2  = -2*error*a1
            db = -2*error*1
            dw11 = (-2*error*w1)(g(z1)*(1-g(z1)))*x[0]
            
            # Update params
            w1 = w1 + lr*dw1
            w2 = w2 + lr*dw2
            b = b + lr*db            
            w11 = w11 + lr*dw11
            w12 = w11 + lr*dw12
            w21 = w11 + lr*dw21
            w22 = w11 + lr*dw22
            b1 = b1 + lr*db1
            b2 = b2 + lr*db2
            
            
        average_error  = average_error/ n
        print(average_error)

sgd(X_train,y_train)    

NameError: name 'X_train' is not defined

ValueError: operands could not be broadcast together with shapes (4,) (1,2) 